// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0QNbpwlMbgw2ncpUrbfA29-tVuv0YQHU',
    appId: '1:407522503085:android:487ccef3b41ccc0c90d924',
    messagingSenderId: '407522503085',
    projectId: 'flagingdatabase',
    storageBucket: 'flagingdatabase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7WiKZomNWuG0siyGTYdcwFxVygL0pjO0',
    appId: '1:407522503085:ios:9729a0072a82f0ea90d924',
    messagingSenderId: '407522503085',
    projectId: 'flagingdatabase',
    storageBucket: 'flagingdatabase.appspot.com',
    androidClientId: '407522503085-ggcjrv8kfflvlsnibv4asadcd3pp6218.apps.googleusercontent.com',
    iosClientId: '407522503085-i8g5h1qijdgi3jrav07159d11nokamck.apps.googleusercontent.com',
    iosBundleId: 'com.seemaster.flaging',
  );
}
